### ISSUE TITLE
Atualização de uma URL Amigável já preenchida

### ISSUE THREAD

**Issue by ghost** [opencartbrasil/url-amigavel-automatica#1]
Boa tarde, o sistema é fantástico, porém ele poderia verificar se o campo já está preenchido, pois vejo que ele substitui o texto que já tiver inserido.

**Comment by v5mvidal** [comment]
Será incluído na próxima release.

**Comment by ghost** [comment]
Saudades da Opencart, há tempos que não vejo uma. Tentamos por anos manter mas não foi possível, entendo que não seja nada fácil manter um OPENSOURCE sem comunidade presente e recurso financeiro. Sucesso.
