### ISSUE TITLE
Erro no console Uncaught SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by TheMasterRoot** [opencartbrasil/url-amigavel-automatica#2]
Boa tarde. instalei o modulo em uma opencart 3.0.2.0 e estou tendo o seguinte erro

`index.php?route=catalog/product/edit&user_token=6fC9ISRWoSMFElXgio8QRHvsOCxpqVBa&product_id=253:657 Uncaught SyntaxError: Unexpected token ':'`

![image](https://user-images.githubusercontent.com/7121027/106369089-612dc600-632d-11eb-9e3f-a3924ca9c688.png)

Pode me ajudar por favor?

**Comment by v5mvidal** [comment]
Este erro está sendo causado por algum problema específico em sua versão do OpenCart, pois testei em uma versão 3.0.2.0 instalada do zero e tudo funcionou conforme o esperado.
